### ISSUE TITLE
Broken Link in Repository Description

### ISSUE THREAD

**Issue by Smart-SangGe** [hack-chat/3rd-party-software-list#30]
Hello,

I wanted to bring to your attention that the link provided in the repository description for [docker-hacker-chat](https://github.com/McGriddle/docker-hacker-chat) appears to be broken. When attempting to access the link, it results in an error or a page not found message.

**Comment by marzavec** [comment]
Oh, good catch, thank you. I've gone ahead and removed it. I have also removed the other docker image link, because it does not reference hack.chat at all anymore.
